export const seedUsers = [
  {
    name: "Admin User",
    username: "admin",
    password: "admin123",
    role: "ADMIN",
    gender: "male",
    dateOfBirth: new Date("1990-01-15"),
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    className: "",
    subjects: [],
    attendance: {
      totalDays: 0,
      presentDays: 0,
      percentage: 0,
    },
  },
  {
    name: "John Doe",
    username: "john.doe",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1995-05-20"),
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    className: "Engineering",
    subjects: ["Mathematics", "Physics", "Computer Science"],
    attendance: {
      totalDays: 100,
      presentDays: 95,
      percentage: 95,
    },
  },
  {
    name: "Jane Smith",
    username: "jane.smith",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1998-08-12"),
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    className: "Business",
    subjects: ["Economics", "Marketing", "Management"],
    attendance: {
      totalDays: 100,
      presentDays: 88,
      percentage: 88,
    },
  },
  {
    name: "Mike Johnson",
    username: "mike.johnson",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1992-03-25"),
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    className: "Design",
    subjects: ["Graphic Design", "UI/UX", "Typography"],
    attendance: {
      totalDays: 100,
      presentDays: 92,
      percentage: 92,
    },
  },
  {
    name: "Sarah Williams",
    username: "sarah.williams",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1996-11-08"),
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    className: "Science",
    subjects: ["Chemistry", "Biology", "Research Methods"],
    attendance: {
      totalDays: 100,
      presentDays: 97,
      percentage: 97,
    },
  },
  {
    name: "David Brown",
    username: "david.brown",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1991-04-10"),
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    className: "Engineering",
    subjects: ["Mechanics", "Thermodynamics"],
    attendance: { totalDays: 100, presentDays: 90, percentage: 90 },
  },
  {
    name: "Emily Davis",
    username: "emily.davis",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1997-09-17"),
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    className: "Business",
    subjects: ["Finance", "Accounting"],
    attendance: { totalDays: 100, presentDays: 93, percentage: 93 },
  },
  {
    name: "Chris Martin",
    username: "chris.martin",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1993-02-14"),
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    className: "Computer Science",
    subjects: ["AI", "Data Structures"],
    attendance: { totalDays: 100, presentDays: 96, percentage: 96 },
  },
  {
    name: "Olivia Thompson",
    username: "olivia.thompson",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1999-12-02"),
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    className: "Design",
    subjects: ["UI/UX", "Color Theory"],
    attendance: { totalDays: 100, presentDays: 89, percentage: 89 },
  },
  {
    name: "Daniel Anderson",
    username: "daniel.anderson",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1994-06-29"),
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    className: "Science",
    subjects: ["Physics", "Astronomy"],
    attendance: { totalDays: 100, presentDays: 94, percentage: 94 },
  },
  {
    name: "Sophia Moore",
    username: "sophia.moore",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1998-03-13"),
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    className: "Engineering",
    subjects: ["Robotics", "Circuits"],
    attendance: { totalDays: 100, presentDays: 91, percentage: 91 },
  },
  {
    name: "James Taylor",
    username: "james.taylor",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1992-10-21"),
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    className: "Business",
    subjects: ["Management", "Leadership"],
    attendance: { totalDays: 100, presentDays: 92, percentage: 92 },
  },
  {
    name: "Ava Martinez",
    username: "ava.martinez",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1997-07-30"),
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    className: "Design",
    subjects: ["Illustration", "Branding"],
    attendance: { totalDays: 100, presentDays: 95, percentage: 95 },
  },
  {
    name: "Matthew Harris",
    username: "matthew.harris",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1996-11-25"),
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    className: "Science",
    subjects: ["Biology", "Genetics"],
    attendance: { totalDays: 100, presentDays: 88, percentage: 88 },
  },
  {
    name: "Isabella Clark",
    username: "isabella.clark",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1995-05-05"),
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    className: "Computer Science",
    subjects: ["Databases", "Operating Systems"],
    attendance: { totalDays: 100, presentDays: 97, percentage: 97 },
  },
  {
    name: "Benjamin Lewis",
    username: "benjamin.lewis",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1991-01-18"),
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    className: "Engineering",
    subjects: ["CAD", "Material Science"],
    attendance: { totalDays: 100, presentDays: 93, percentage: 93 },
  },
  {
    name: "Mia Young",
    username: "mia.young",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1998-04-08"),
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    className: "Business",
    subjects: ["Marketing", "HR"],
    attendance: { totalDays: 100, presentDays: 94, percentage: 94 },
  },
  {
    name: "Alexander Walker",
    username: "alexander.walker",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1993-09-11"),
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    className: "Design",
    subjects: ["3D Modeling", "Animation"],
    attendance: { totalDays: 100, presentDays: 90, percentage: 90 },
  },
  {
    name: "Charlotte Hall",
    username: "charlotte.hall",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1994-01-27"),
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    className: "Science",
    subjects: ["Chemistry", "Lab Safety"],
    attendance: { totalDays: 100, presentDays: 92, percentage: 92 },
  },
  {
    name: "Henry Allen",
    username: "henry.allen",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1990-07-14"),
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    className: "Business",
    subjects: ["Finance", "Economics"],
    attendance: { totalDays: 100, presentDays: 96, percentage: 96 },
  },
  {
    name: "Amelia Scott",
    username: "amelia.scott",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1997-03-03"),
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    className: "Design",
    subjects: ["Photography", "Visual Design"],
    attendance: { totalDays: 100, presentDays: 90, percentage: 90 },
  },
  {
    name: "Wyatt Green",
    username: "wyatt.green",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1996-06-06"),
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    className: "Computer Science",
    subjects: ["Cybersecurity", "Networking"],
    attendance: { totalDays: 100, presentDays: 98, percentage: 98 },
  },
  {
    name: "Harper Adams",
    username: "harper.adams",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1999-01-19"),
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
    className: "Engineering",
    subjects: ["Control Systems", "Dynamics"],
    attendance: { totalDays: 100, presentDays: 87, percentage: 87 },
  },
  {
    name: "Logan Baker",
    username: "logan.baker",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1995-08-22"),
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    className: "Science",
    subjects: ["Microbiology", "Ecology"],
    attendance: { totalDays: 100, presentDays: 91, percentage: 91 },
  },
  {
    name: "Evelyn Nelson",
    username: "evelyn.nelson",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1993-02-28"),
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    className: "Business",
    subjects: ["Entrepreneurship", "Business Law"],
    attendance: { totalDays: 100, presentDays: 93, percentage: 93 },
  },
  {
    name: "Jack Carter",
    username: "jack.carter",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1992-12-12"),
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
    className: "Computer Science",
    subjects: ["Algorithms", "Web Development"],
    attendance: { totalDays: 100, presentDays: 99, percentage: 99 },
  },
  {
    name: "Grace Mitchell",
    username: "grace.mitchell",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1996-09-09"),
    avatar: "https://randomuser.me/api/portraits/women/13.jpg",
    className: "Design",
    subjects: ["Art Theory", "Illustration"],
    attendance: { totalDays: 100, presentDays: 90, percentage: 90 },
  },
  {
    name: "Owen Perez",
    username: "owen.perez",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1997-03-23"),
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    className: "Engineering",
    subjects: ["Fluid Mechanics", "Solid Mechanics"],
    attendance: { totalDays: 100, presentDays: 92, percentage: 92 },
  },
  {
    name: "Chloe Roberts",
    username: "chloe.roberts",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1998-07-17"),
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    className: "Science",
    subjects: ["Organic Chemistry", "Botany"],
    attendance: { totalDays: 100, presentDays: 94, percentage: 94 },
  },
  {
    name: "Samuel Turner",
    username: "samuel.turner",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1994-10-01"),
    avatar: "https://randomuser.me/api/portraits/men/16.jpg",
    className: "Business",
    subjects: ["Marketing Strategy", "Finance"],
    attendance: { totalDays: 100, presentDays: 89, percentage: 89 },
  },
  {
    name: "Zoe Phillips",
    username: "zoe.phillips",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1999-06-04"),
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
    className: "Computer Science",
    subjects: ["Full Stack", "Cloud Computing"],
    attendance: { totalDays: 100, presentDays: 98, percentage: 98 },
  },
  {
    name: "Nathan Campbell",
    username: "nathan.campbell",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1995-02-06"),
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    className: "Design",
    subjects: ["UI Design", "Motion Graphics"],
    attendance: { totalDays: 100, presentDays: 91, percentage: 91 },
  },
  {
    name: "Lily Parker",
    username: "lily.parker",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1994-11-11"),
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    className: "Engineering",
    subjects: ["Manufacturing", "Automation"],
    attendance: { totalDays: 100, presentDays: 95, percentage: 95 },
  },
  {
    name: "Hunter Edwards",
    username: "hunter.edwards",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1997-01-09"),
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
    className: "Science",
    subjects: ["Geology", "Environmental Science"],
    attendance: { totalDays: 100, presentDays: 88, percentage: 88 },
  },
  {
    name: "Layla Collins",
    username: "layla.collins",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1998-10-15"),
    avatar: "https://randomuser.me/api/portraits/women/17.jpg",
    className: "Business",
    subjects: ["Brand Strategy", "Economics"],
    attendance: { totalDays: 100, presentDays: 92, percentage: 92 },
  },
  {
    name: "Ethan Stewart",
    username: "ethan.stewart",
    password: "password123",
    role: "EMPLOYEE",
    gender: "male",
    dateOfBirth: new Date("1993-05-16"),
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    className: "Computer Science",
    subjects: ["AI", "ML"],
    attendance: { totalDays: 100, presentDays: 97, percentage: 97 },
  },
  {
    name: "Scarlett Morris",
    username: "scarlett.morris",
    password: "password123",
    role: "EMPLOYEE",
    gender: "female",
    dateOfBirth: new Date("1996-12-28"),
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    className: "Design",
    subjects: ["Digital Art", "Typography"],
    attendance: { totalDays: 100, presentDays: 93, percentage: 93 },
  },
];
